# Script generated by SupremolecularAnalyser
import os.path
import sys

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_DIR, "pymol_plugin", "supramolecular"))

import matplotlib.pyplot as plt
from simple_filters import simple_merge
import pandas as pd
import numpy as np
import matplotlib as mpl
from os.path import isdir, join, basename
from os import makedirs, remove
from glob import glob
from itertools import combinations
from math import pi

mpl.rcParams["mathtext.default"] = "regular"
plt.rcParams.update({"font.size": 16})

log_dir = "logs/"
postprocessing_dir = "postprocessing/"
res_unique_dir = join(postprocessing_dir, "general")

if not isdir(res_unique_dir):
    makedirs(res_unique_dir)

# cases2run = { "preprocessing" : True, "a-g" : True, "UniqueSeq" : True,  "histogram2d" : True,
#        "histogram2d-planar" : True, "histograms-linear" : True , "barplots": True , "resolutionplot":False,
#        "occurencesTable" : True, "occurencesPairs" : True,
#        "chainNeoghbors" : True }

cases2run = {
    "preprocessing": False,
    "a-g": False,
    "UniqueSeq": False,
    "histogram2d": True,
    "hydrogenBondAnalysis": False,
    "ligandsAnalysis": False,
    "histogram2d-planar": False,
    "histograms-linear": False,
    "barplots": False,
    "resolutionplot": False,
    "occurencesTable": False,
    "occurencesPairs": False,
    "chainNeoghbors": False,
}


def save_unique_records_seq(log_path, log_out, chain1_key, chain2_key, headers_subset):
    print("Processing: ", log_path)

    unique_seq_df = pd.read_csv("chainClusters.csv", sep="\t")

    unique_seq_df1 = unique_seq_df.rename(
        columns={"Chain": chain1_key, "Sequence ID": "Sequence ID 1"}
    )
    unique_seq_df2 = unique_seq_df.rename(
        columns={"Chain": chain2_key, "Sequence ID": "Sequence ID 2"}
    )

    df = pd.read_table(log_path)

    df = pd.merge(
        df, unique_seq_df1, on=["PDB Code", chain1_key], how="left", indicator=True
    )
    df = df.rename(columns={"_merge": "seq1 origin"})
    df = pd.merge(
        df, unique_seq_df2, on=["PDB Code", chain2_key], how="left", indicator=True
    )
    df = df.rename(columns={"_merge": "seq2 origin"})
    df = df.sort_values(by=["Distance"], ascending=True)

    df_recognised_seq_same_chains = df[
        ((df["seq1 origin"] == "both") | (df["seq2 origin"] == "both"))
        & (df[chain1_key] == df[chain2_key])
    ].drop_duplicates(subset=headers_subset + ["Sequence ID 1", "Sequence ID 2"])
    df_recognised_seq_different_chains = df[
        ((df["seq1 origin"] == "both") | (df["seq2 origin"] == "both"))
        & (df[chain1_key] != df[chain2_key])
    ].drop_duplicates(subset=headers_subset + ["Sequence ID 1", "Sequence ID 2"])

    df_not_recognised_seq = df[
        (df["seq1 origin"] == "left_only") & (df["seq2 origin"] == "left_only")
    ].drop_duplicates(subset=headers_subset + ["PDB Code"])

    df = pd.concat(
        [
            df_recognised_seq_same_chains,
            df_recognised_seq_different_chains,
            df_not_recognised_seq,
        ],
        ignore_index=True,
    )

    df.to_csv(log_out, sep="\t")
    num_lines = sum(1 for line in open(log_out)) - 1
    num_lines2 = sum(1 for line in open(log_path)) - 1

    print(num_lines)
    print(num_lines2)

    return log_out


log_anion_pi = join(log_dir, "anionPi.log")
log_anion_cation = join(log_dir, "anionCation.log")
log_cation_pi = join(log_dir, "cationPi.log")
log_pi_pi = join(log_dir, "piPi.log")
log_methyl_pi = join(log_dir, "methylPi.log")
log_planar_anion_pi = join(log_dir, "planarAnionPi.log")
log_linear_anion_pi = join(log_dir, "linearAnionPi.log")

if cases2run["preprocessing"] or cases2run["a-g"]:
    anion_pi = (
        pd.read_csv(log_anion_pi, sep="\t")
        .fillna("NA")
        .sort_values(by=["Distance"], ascending=True)
    )
    anion_pi = anion_pi.drop_duplicates(
        subset=[
            "PDB Code",
            "Model No",
            "Anion chain",
            "Pi acid chain",
            "Pi acid Code",
            "Piacid id",
            "Anion code",
            "Anion id",
            "Anion group id",
        ]
    )
    anion_pi = anion_pi[
        ~anion_pi["Anion code"]
        .astype(str)
        .isin(["FES", "F3S", "S3F", "9S8", "ER2", "FS4", "MSK", "SF4", "1CL", "CLF"])
    ]
    # LinearAnionPi = pd.read_csv( logdir+"linearAnionPi.log", sep = "\t").fillna("NA")

    anion_cation = pd.read_csv(log_anion_cation, sep="\t").fillna("NA")
    anion_cation = anion_cation[
        ~anion_cation["Anion code"]
        .astype(str)
        .isin(["FES", "F3S", "S3F", "9S8", "ER2", "FS4", "MSK", "SF4", "1CL", "CLF"])
    ]

    h_bonds = pd.read_csv(log_dir + "hBonds.log", sep="\t").fillna("NA")
    h_bonds = h_bonds[
        ~h_bonds["Anion code"]
        .astype(str)
        .isin(["FES", "F3S", "S3F", "9S8", "ER2", "FS4", "MSK", "SF4", "1CL", "CLF"])
    ]

    cation_pi = pd.read_csv(log_cation_pi, sep="\t").fillna("NA")
    pi_pi = pd.read_csv(log_pi_pi, sep="\t").fillna("NA")
    # MetalLigand = pd.read_csv( logdir+"metalLigand.log", sep = "\t").fillna("NA")
    # PlanarAnionPi = pd.read_csv( logPlanarAnionPi, sep = "\t").fillna("NA")
if cases2run["preprocessing"]:
    methyl_pi = pd.read_csv(log_methyl_pi, sep="\t").fillna("NA")

resolution = pd.read_csv("resolu.idx", sep=r"\s+")
res_ok = resolution[(resolution["RESOLUTION"] <= 2.5) & (resolution["RESOLUTION"] > 0)][
    "IDCODE"
]
print("PDB ok: ", len(res_ok))
##################################################################################################
log_anion_pi_res = join(res_unique_dir, "anionPi_res.log")
log_methyl_pi_res = join(res_unique_dir, "methylPi_res.log")
log_cation_pi_res = join(res_unique_dir, "cationPi_res.log")
log_pi_pi_res = join(res_unique_dir, "piPi_res.log")

if cases2run["preprocessing"]:

    def keep_high_resolution(df, log_name):
        df_temp = df[df["PDB Code"].isin(res_ok)]
        # logName = join(resUniqueDir, baseName+"_res.log")
        df_temp.to_csv(log_name, sep="\t")
        return log_name

    keep_high_resolution(anion_pi, log_anion_pi_res)
    keep_high_resolution(methyl_pi, log_methyl_pi_res)
    keep_high_resolution(cation_pi, log_cation_pi_res)
    keep_high_resolution(pi_pi, log_pi_pi_res)


##################################################################################################
log_anion_pi_res_ring_plane = join(res_unique_dir, "anionPi_res_ring_plane.log")

if cases2run["preprocessing"]:
    anion_pi_temp = anion_pi
    anion_pi_temp = anion_pi_temp[anion_pi_temp["x"] > 3]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["x"] < 4.9]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] < 1]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Distance" ] <= 4.5 ]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["PDB Code"].isin(res_ok)]
    anion_pi_temp.to_csv(log_anion_pi_res_ring_plane, sep="\t")

##################################################################################################
log_anion_pi_res_cylinder = join(res_unique_dir, "anionPi_res_cylinder.log")

if cases2run["preprocessing"]:
    anion_pi_temp = anion_pi
    anion_pi_temp = anion_pi_temp[anion_pi_temp["x"] < 1.8]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] > 1.5]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] < 4.5]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["PDB Code"].isin(res_ok)]
    anion_pi_temp.to_csv(log_anion_pi_res_cylinder, sep="\t")

##################################################################################################
log_anion_pi_res_bullshit = join(res_unique_dir, "anionPi_res_bullshit.log")

if cases2run["preprocessing"]:
    anion_pi_temp = anion_pi
    anion_pi_temp = anion_pi_temp[anion_pi_temp["Distance"] < 5.0]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["Angle"] < 30]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["PDB Code"].isin(res_ok)]
    anion_pi_temp.to_csv(log_anion_pi_res_bullshit, sep="\t")

##################################################################################################
log_anion_pi_res_diag = join(res_unique_dir, "anionPi_res_norCylinderNorPlane.log")

if cases2run["preprocessing"]:
    anion_pi_temp = anion_pi
    anion_pi_temp = anion_pi_temp[anion_pi_temp["x"] > 1.8]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["x"] < 3.25]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] > 2.4]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] < 3.8]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["PDB Code"].isin(res_ok)]
    anion_pi_temp.to_csv(log_anion_pi_res_diag, sep="\t")

##################################################################################################

log_cation_pi_res_cylinder = join(res_unique_dir, "cationPi_res_cylinder.log")

if cases2run["preprocessing"]:
    cation_pi_temp = cation_pi
    cation_pi_temp = cation_pi_temp[cation_pi_temp["x"] < 1.8]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["h"] > 1.5]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["h"] < 4.5]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["PDB Code"].isin(res_ok)]
    cation_pi_temp.to_csv(log_cation_pi_res_cylinder, sep="\t")

##################################################################################################

log_cation_pi_res_ring_plane = join(res_unique_dir, "cationPi_res_ring_plane.log")

if cases2run["preprocessing"]:
    cation_pi_temp = cation_pi
    cation_pi_temp = cation_pi_temp[cation_pi_temp["x"] > 3]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["h"] < 1]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["x"] < 4.9]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["PDB Code"].isin(res_ok)]
    cation_pi_temp.to_csv(log_cation_pi_res_ring_plane, sep="\t")

##################################################################################################

# logAnionPi45 = join(resUniqueDir, "anionPi_45.log")
# logAnionPiRes45 = join(resUniqueDir, "anionPi_res_45.log")

# if cases2run["preprocessing"]:
#   AnionPi_temp = AnionPi
#   AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Distance" ] <= 4.5 ]
#   AnionPi_temp.to_csv( logAnionPi45, sep = "\t")
#   AnionPi_temp = AnionPi_temp[ AnionPi_temp ['PDB Code'].isin(resOK)]
#   AnionPi_temp.to_csv( logAnionPiRes45, sep = "\t")

log_cation_pi_res45 = join(res_unique_dir, "cationPi_res_45.log")

if cases2run["preprocessing"]:
    cation_pi_temp = cation_pi
    cation_pi_temp = cation_pi_temp[cation_pi_temp["Distance"] <= 5.0]
    cation_pi_temp = cation_pi_temp[cation_pi_temp["PDB Code"].isin(res_ok)]
    cation_pi_temp.to_csv(log_cation_pi_res45, sep="\t")

##################################################################################################
dist_anion_cation = 3.25

for dirname, anion_pi_source in zip(
    ["cylinder", "ringPlane", "norCylinderNodPlane"],
    [log_anion_pi_res_cylinder, log_anion_pi_res_ring_plane, log_anion_pi_res_diag],
):
    print("A-G Analysis")
    print(anion_pi_source)
    anion_pi = pd.read_csv(anion_pi_source, sep="\t").fillna("NA")

    analyse_dir = join(postprocessing_dir, dirname)

    ##################################################################################################
    a_dir = join(analyse_dir, "a")
    if not isdir(a_dir):
        makedirs(a_dir)
    log_anion_pi_a = join(a_dir, "anionPi.log")
    log_cation_pi_a = join(a_dir, "cationPi.log")
    log_anion_cation_a = join(a_dir, "anionCation.log")

    if cases2run["a-g"]:
        print("Starting case a")

        anion_pi_temp = anion_pi

        cation_pi_temp = cation_pi
        cation_pi_temp = cation_pi_temp[
            cation_pi_temp["RingChain"].astype(str).isin(["1"])
        ]

        data_frames2_merge = [anion_pi_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ]
        ]
        data_frames2_exclude = [cation_pi_temp]
        data_frame_exclude_headers = [
            [
                "PDB Code",
                "Model No",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ]
        ]

        [anion_pi_temp, cation_pi_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        cation_pi_temp = cation_pi
        cation_pi_temp = cation_pi_temp[
            cation_pi_temp["RingChain"].astype(str).isin(["0"])
        ]
        cation_pi_temp = cation_pi_temp[
            ~cation_pi_temp["Cation code"].astype(str).isin(["ARG", "LYS"])
        ]

        anion_cation_temp = anion_cation
        anion_cation_temp = anion_cation_temp[
            anion_cation_temp["Distance"] < dist_anion_cation
        ]
        if dirname != "ringPlane":
            anion_cation_temp = anion_cation_temp[
                anion_cation_temp["Same semisphere"].astype(str).isin(["True"])
            ]
        anion_cation_temp = anion_cation_temp[
            ~anion_cation_temp["Cation code"].astype(str).isin(["ARG", "LYS"])
        ]

        # Check whether there are cations on the opposite side of the ring, and how many

        data_frames2_merge = [anion_pi_temp, cation_pi_temp, anion_cation_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, cation_pi_temp, anion_cation_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_a, sep="\t")
        cation_pi_temp.to_csv(log_cation_pi_a, sep="\t")
        anion_cation_temp.to_csv(log_anion_cation_a, sep="\t")

    ##################################################################################################
    b_dir = join(analyse_dir, "b")
    if not isdir(b_dir):
        makedirs(b_dir)

    log_anion_pi_b = join(b_dir, "anionPi.log")
    log_cation_pi_b = join(b_dir, "cationPi.log")
    log_anion_cation_b = join(b_dir, "anionCation.log")

    if cases2run["a-g"]:
        print("Starting case b")

        anion_pi_temp = anion_pi

        cation_pi_temp = cation_pi
        cation_pi_temp = cation_pi_temp[
            cation_pi_temp["RingChain"].astype(str).isin(["1"])
        ]

        data_frames2_merge = [anion_pi_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ]
        ]
        data_frames2_exclude = [cation_pi_temp]
        data_frame_exclude_headers = [
            [
                "PDB Code",
                "Model No",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ]
        ]

        [anion_pi_temp, cation_pi_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_cation_temp = anion_cation
        anion_cation_temp = anion_cation_temp[
            anion_cation_temp["Distance"] > dist_anion_cation
        ]
        if dirname != "ringPlane":
            anion_cation_temp = anion_cation_temp[
                anion_cation_temp["Same semisphere"].astype(str).isin(["False"])
            ]

        cation_pi_temp = cation_pi
        cation_pi_temp = cation_pi_temp[
            ~cation_pi_temp["RingChain"].astype(str).isin(["1"])
        ]
        cation_pi_temp = cation_pi_temp[cation_pi_temp["Distance"] < 5.0]
        cation_pi_temp = cation_pi_temp[cation_pi_temp["Angle"] < 45.0]

        data_frames2_merge = [anion_pi_temp, cation_pi_temp, anion_cation_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, cation_pi_temp, anion_cation_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_b, sep="\t")
        cation_pi_temp.to_csv(log_cation_pi_b, sep="\t")
        anion_cation_temp.to_csv(log_anion_cation_b, sep="\t")

    ##################################################################################################
    c_dir = join(analyse_dir, "c")
    if not isdir(c_dir):
        makedirs(c_dir)

    log_anion_pi_c = join(c_dir, "anionPi.log")
    log_cation_pi_c = join(c_dir, "cationPi.log")
    log_anion_cation_c = join(c_dir, "anionCation.log")

    if cases2run["a-g"]:
        print("Starting case c")

        anion_pi_temp = anion_pi

        cation_pi_temp = cation_pi
        cation_pi_temp = cation_pi_temp[
            cation_pi_temp["RingChain"].astype(str).isin(["1"])
        ]

        anion_cation_temp = anion_cation
        anion_cation_temp = anion_cation_temp[
            anion_cation_temp["Distance"] < dist_anion_cation
        ]

        data_frames2_merge = [anion_pi_temp, cation_pi_temp, anion_cation_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, cation_pi_temp, anion_cation_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_c, sep="\t")
        cation_pi_temp.to_csv(log_cation_pi_c, sep="\t")
        anion_cation_temp.to_csv(log_anion_cation_c, sep="\t")

    ##################################################################################################
    d_dir = join(analyse_dir, "d")
    if not isdir(d_dir):
        makedirs(d_dir)

    log_anion_pi_d = join(d_dir, "anionPi.log")
    log_pi_pi_d = join(d_dir, "piPi.log")

    if cases2run["a-g"]:
        print("Starting case d")

        anion_pi_temp = anion_pi

        pi_pi_temp = pi_pi
        pi_pi_temp = pi_pi_temp[pi_pi_temp["h"] > 1.6]
        pi_pi_temp = pi_pi_temp[pi_pi_temp["x"] < 2.2]
        pi_pi_temp = pi_pi_temp[pi_pi_temp["Angle"] < 15.0]
        pi_pi_temp = pi_pi_temp[pi_pi_temp["theta"] < 15.0]

        data_frames2_merge = [anion_pi_temp, pi_pi_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, pi_pi_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_d, sep="\t")
        pi_pi_temp.to_csv(log_pi_pi_d, sep="\t")

    ##################################################################################################
    e_dir = join(analyse_dir, "e")
    if not isdir(e_dir):
        makedirs(e_dir)

    log_anion_pi_e = join(e_dir, "anionPi.log")
    log_pi_pi_e = join(e_dir, "piPi.log")

    if cases2run["a-g"]:
        print("Starting case e")

        anion_pi_temp = anion_pi

        pi_pi_temp = pi_pi
        pi_pi_temp = pi_pi_temp[pi_pi_temp["Angle"] > 70.0]
        pi_pi_temp = pi_pi_temp[pi_pi_temp["theta"] > 70.0]
        pi_pi_temp = pi_pi_temp[pi_pi_temp["omega"] > 70.0]

        data_frames2_merge = [anion_pi_temp, pi_pi_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, pi_pi_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_e, sep="\t")
        pi_pi_temp.to_csv(log_pi_pi_e, sep="\t")

    ##################################################################################################
    f_dir = join(analyse_dir, "f")
    if not isdir(f_dir):
        makedirs(f_dir)

    log_anion_pi_f = join(f_dir, "anionPi.log")
    log_cation_pi_f = join(f_dir, "cationPi.log")
    log_anion_cation_f = join(f_dir, "anionCation.log")

    if cases2run["a-g"]:
        print("Starting case f")

        anion_pi_temp = anion_pi

        anion_cation_temp = anion_cation
        anion_cation_temp = anion_cation_temp[anion_cation_temp["Distance"] < 3.5]

        data_frames2_merge = [anion_pi_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ]
        ]
        data_frames2_exclude = [anion_cation_temp]
        data_frame_exclude_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ]
        ]

        [anion_pi_temp, anion_cation_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_cation_temp = anion_cation
        anion_cation_temp = anion_cation_temp[anion_cation_temp["Distance"] > 3.5]

        cation_pi_temp = cation_pi
        cation_pi_temp = cation_pi_temp[cation_pi_temp["RingChain"] > 0.1]

        data_frames2_merge = [anion_pi_temp, cation_pi_temp, anion_cation_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Cation code",
                "Cation chain",
                "Cation id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, cation_pi_temp, anion_cation_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_f, sep="\t")
        cation_pi_temp.to_csv(log_cation_pi_f, sep="\t")
        anion_cation_temp.to_csv(log_anion_cation_f, sep="\t")

    ##################################################################################################
    g_dir = join(analyse_dir, "g")
    if not isdir(g_dir):
        makedirs(g_dir)

    log_anion_pi_g = join(g_dir, "anionPi.log")
    log_h_bonds_g = join(g_dir, "hbond.log")

    if cases2run["a-g"]:
        print("Starting case g")

        anion_pi_temp = anion_pi
        # Parameters to tune: angle 170-180, H-acceptor 1.2-1.5, donor-acceptor 2.4-3
        h_bonds_temp = h_bonds
        h_bonds_temp = h_bonds_temp[h_bonds_temp["Angle"] > 130.0]
        h_bonds_temp = h_bonds_temp[h_bonds_temp["Angle"] < 180.0]
        # HBonds_temp = HBonds_temp[ HBonds_temp [ "Distance Don Acc" ] > 2.2 ]
        h_bonds_temp = h_bonds_temp[h_bonds_temp["Distance Don Acc"] < 3.2]
        # HBonds_temp = HBonds_temp[ HBonds_temp [ "Distance H Acc" ] > 1.2 ]
        h_bonds_temp = h_bonds_temp[h_bonds_temp["Distance H Acc"] < 2.2]

        data_frames2_merge = [anion_pi_temp, h_bonds_temp]
        data_frame_merge_headers = [
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
                "Pi acid Code",
                "Pi acid chain",
                "Piacid id",
                "CentroidId",
            ],
            [
                "PDB Code",
                "Model No",
                "Anion code",
                "Anion chain",
                "Anion id",
                "Anion group id",
            ],
        ]
        data_frames2_exclude = []
        data_frame_exclude_headers = []

        [anion_pi_temp, h_bonds_temp] = simple_merge(
            data_frames2_merge,
            data_frame_merge_headers,
            data_frames2_exclude,
            data_frame_exclude_headers,
        )

        anion_pi_temp.to_csv(log_anion_pi_g, sep="\t")
        h_bonds_temp.to_csv(log_h_bonds_g, sep="\t")

    ##################################################################################################
    pure_anion_pi_dir = join(analyse_dir, "pureAnionPi")
    if not isdir(pure_anion_pi_dir):
        makedirs(pure_anion_pi_dir)

    log_anion_pi_pure = join(pure_anion_pi_dir, "anionPi.log")
    if cases2run["a-g"]:
        cases2exclude = [
            log_anion_pi_a,
            log_anion_pi_b,
            log_anion_pi_c,
            log_anion_pi_d,
            log_anion_pi_e,
            log_anion_pi_f,
            log_anion_pi_g,
        ]

        df = anion_pi
        merging_headers = [
            "PDB Code",
            "Model No",
            "Anion code",
            "Anion chain",
            "Anion id",
            "Anion group id",
            "Pi acid Code",
            "Pi acid chain",
            "Piacid id",
        ]
        for log_path in cases2exclude:
            # print("lol")
            df2exclude = pd.read_table(log_path)

            sub_merged = pd.merge(
                df,
                df2exclude[merging_headers],
                on=merging_headers,
                how="left",
                indicator=True,
            )
            df = sub_merged[sub_merged["_merge"] == "left_only"]
            df = df.drop(["_merge"], axis=1)

        df.to_csv(log_anion_pi_pure, sep="\t")

    ##################################################################################################

    if cases2run["a-g"]:
        files2process = [
            log_anion_pi_a,
            log_anion_pi_b,
            log_anion_pi_c,
            log_anion_pi_d,
            log_anion_pi_e,
            log_anion_pi_f,
            log_anion_pi_g,
            log_anion_pi_pure,
        ]

        for f in files2process:
            f_out = f[:-4] + "_UniqueSeq.log"
            save_unique_records_seq(
                f,
                f_out,
                "Anion chain",
                "Pi acid chain",
                [
                    "Pi acid Code",
                    "Piacid id",
                    "Anion code",
                    "Anion id",
                    "Anion group id",
                ],
            )

        for f in [log_cation_pi_a, log_cation_pi_b, log_cation_pi_c, log_cation_pi_f]:
            f_out = f[:-4] + "_UniqueSeq.log"
            save_unique_records_seq(
                f,
                f_out,
                "Cation chain",
                "Pi acid chain",
                ["Pi acid Code", "Piacid id", "Cation code", "Cation id"],
            )

        for f in [log_pi_pi_d, log_pi_pi_e]:
            f_out = f[:-4] + "_UniqueSeq.log"
            save_unique_records_seq(
                f,
                f_out,
                "Pi res chain",
                "Pi acid chain",
                ["Pi acid Code", "Piacid id", "Pi res code", "Pi res id"],
            )

    ##################################################################################################

    if cases2run["a-g"]:

        def get_freq_anion_pi(df):
            dfanion = df.drop_duplicates(
                subset=["Anion code", "Anion id", "Anion group id", "Sequence ID 1"]
            )
            dfpiacid = df.drop_duplicates(
                subset=["Pi acid Code", "Piacid id", "Sequence ID 2"]
            )
            dfpiacid_anion = df.drop_duplicates(
                subset=[
                    "Pi acid Code",
                    "Piacid id",
                    "Anion code",
                    "Anion id",
                    "Anion group id",
                    "Sequence ID 1",
                    "Sequence ID 2",
                ]
            )

            anion_freq = (
                dfanion.groupby("Anion code").size().sort_values(ascending=False)
            )
            pi_acid_freq = (
                dfpiacid.groupby("Pi acid Code").size().sort_values(ascending=False)
            )
            pi_acid_anion_freq = (
                dfpiacid_anion.groupby(["Pi acid Code", "Anion code"])
                .size()
                .sort_values(ascending=False)
            )

            anion_dict = anion_freq.to_dict()
            pi_acid_freq_dict = pi_acid_freq.to_dict()
            pi_acid_anion_dict = pi_acid_anion_freq.to_dict()

            return anion_dict, pi_acid_freq_dict, pi_acid_anion_dict

        def get_freq_cation(df):
            dfcation = df.drop_duplicates(
                subset=["Sequence ID 1", "Cation code", "Cation id"]
            )
            dfpiacid = df.drop_duplicates(
                subset=["Sequence ID 2", "Pi acid Code", "Piacid id"]
            )

            cation_freq = (
                dfcation.groupby("Cation code").size().sort_values(ascending=False)
            )
            pi_acid_freq = (
                dfpiacid.groupby("Pi acid Code").size().sort_values(ascending=False)
            )
            element_freq = (
                dfcation.groupby("Atom symbol").size().sort_values(ascending=False)
            )

            cation_dict = cation_freq.to_dict()
            pi_acid_freq_dict = pi_acid_freq.to_dict()
            element_dict = element_freq.to_dict()

            return cation_dict, pi_acid_freq_dict, element_dict

        files2process = [
            log_anion_pi_a,
            log_anion_pi_b,
            log_anion_pi_c,
            log_anion_pi_d,
            log_anion_pi_e,
            log_anion_pi_f,
            log_anion_pi_g,
            log_anion_pi_pure,
        ]

        for f in files2process:
            f_unique = f[:-4] + "_UniqueSeq.log"
            pd_unique = pd.read_table(f_unique)
            an_dict, pi_acid_dict, pairs_dict = get_freq_anion_pi(pd_unique)

            anion_stats = open(f_unique[:-4] + "_anions.csv", "w")
            anion_stats.write("Residue\tOccurences\n")
            for res in an_dict:
                anion_stats.write(res + "\t" + str(an_dict[res]) + "\n")
            anion_stats.close()

            pi_stats = open(f_unique[:-4] + "_piAcids.csv", "w")
            pi_stats.write("Residue\tOccurences\n")
            for res in pi_acid_dict:
                pi_stats.write(res + "\t" + str(pi_acid_dict[res]) + "\n")
            pi_stats.close()

            pair_stats = open(f_unique[:-4] + "_pairs.csv", "w")
            pair_stats.write("Residue:Residue\tOccurences\n")
            for res in pairs_dict:
                pair_stats.write(
                    res[0] + ":" + res[1] + "\t" + str(pairs_dict[res]) + "\n"
                )
            pair_stats.close()

            png_name = f[:-4] + "_UniqueSeq_hHist.png"
            distances = pd_unique["h"].tolist()

            plt.figure()
            plt.rcParams.update({"font.size": 12})
            n, bins, patches = plt.hist(
                distances, 15, density=False, facecolor="cornflowerblue"
            )
            # plt.colorbar()
            plt.xlabel("$\\it{h}$ / $\\AA$")
            plt.ylabel("Number of occurences")
            # if text != "":
            #   plt.text(70, 0.7*max(n), text, fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
            plt.savefig(png_name, dpi=600, transparent=True)
            plt.close()

            png_name = f[:-4] + "_UniqueSeq_xHist.png"
            x = pd_unique["x"].tolist()

            plt.figure()
            plt.rcParams.update({"font.size": 12})
            n, bins, patches = plt.hist(
                x, 15, density=False, facecolor="cornflowerblue"
            )
            # plt.colorbar()
            plt.xlabel("$\\it{x}$ / $\\AA$")
            plt.ylabel("Number of occurences")
            # if text != "":
            #   plt.text(70, 0.7*max(n), text, fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
            plt.savefig(png_name, dpi=600, transparent=True)
            plt.close()

        for f in [log_cation_pi_a, log_cation_pi_b, log_cation_pi_c, log_cation_pi_f]:
            f_unique = f[:-4] + "_UniqueSeq.log"

            pd_unique = pd.read_table(f_unique)
            cat_dict, pi_acid_cat_dict, cat_el_dict = get_freq_cation(pd_unique)

            cat_el_stats = open(f_unique[:-4] + "_catEl.csv", "w")
            cat_el_stats.write("Element\tOccurences\n")
            for res in cat_el_dict:
                cat_el_stats.write(res + "\t" + str(cat_el_dict[res]) + "\n")
            cat_el_stats.close()

    ##################################################################################################
    if cases2run["a-g"]:
        files2process = [
            log_anion_pi_a,
            log_anion_pi_b,
            log_anion_pi_c,
            log_anion_pi_d,
            log_anion_pi_e,
            log_anion_pi_f,
            log_anion_pi_g,
        ]

        for comb in combinations(files2process, 2):
            merged = pd.read_table(comb[0][:-4] + "_UniqueSeq.log")

            for f in comb[1:]:
                new_data = pd.read_table(f[:-4] + "_UniqueSeq.log")
                headers = [
                    "PDB Code",
                    "Pi acid Code",
                    "Pi acid chain",
                    "Piacid id",
                    "CentroidId",
                    "Anion code",
                    "Anion chain",
                    "Anion id",
                    "Anion group id",
                    "Model No",
                ]
                merged = pd.merge(merged, new_data, on=headers)

            print("intersection between: ")
            print("\n".join(comb))
            print(len(merged.index))

##################################################################################################

log_anion_pi_unique = join(
    res_unique_dir, basename(log_anion_pi)[:-4] + "_UniqueSeq.log"
)
log_anion_pi_res_unique = log_anion_pi_res[:-4] + "_UniqueSeq.log"
log_anion_pi_res_cylinder_unique = log_anion_pi_res_cylinder[:-4] + "_UniqueSeq.log"
log_anion_pi_res_ring_plane_unique = log_anion_pi_res_ring_plane[:-4] + "_UniqueSeq.log"
log_anion_pi_res_diag_unique = log_anion_pi_res_diag[:-4] + "_UniqueSeq.log"
log_anion_pi_res_bullshit_unique = log_anion_pi_res_bullshit[:-4] + "_UniqueSeq.log"
# logAnionPi45Unique = logAnionPi45[:-4] +  "_UniqueSeq.log"
# logAnionPiRes45Unique = logAnionPiRes45[:-4]+  "_UniqueSeq.log"

log_methyl_pi_unique = join(
    res_unique_dir, basename(log_methyl_pi)[:-4] + "_UniqueSeq.log"
)
log_methyl_pi_res_unique = log_methyl_pi_res[:-4] + "_UniqueSeq.log"

log_cation_pi_unique = join(
    res_unique_dir, basename(log_cation_pi)[:-4] + "_UniqueSeq.log"
)
log_cation_pi_res_unique = log_cation_pi_res[:-4] + "_UniqueSeq.log"
log_cation_pi_res45_unique = log_cation_pi_res45[:-4] + "_UniqueSeq.log"
log_cation_pi_res_cylinder_unique = log_cation_pi_res_cylinder[:-4] + "_UniqueSeq.log"
log_cation_pi_res_ring_plane_unique = (
    log_cation_pi_res_ring_plane[:-4] + "_UniqueSeq.log"
)

log_pi_pi_unique = join(res_unique_dir, basename(log_pi_pi)[:-4] + "_UniqueSeq.log")
log_pi_pi_res_unique = log_pi_pi_res[:-4] + "_UniqueSeq.log"

if cases2run["UniqueSeq"]:
    print("unique seq")

    save_unique_records_seq(
        log_anion_pi,
        log_anion_pi_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    save_unique_records_seq(
        log_anion_pi_res,
        log_anion_pi_res_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    save_unique_records_seq(
        log_anion_pi_res_cylinder,
        log_anion_pi_res_cylinder_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    save_unique_records_seq(
        log_anion_pi_res_ring_plane,
        log_anion_pi_res_ring_plane_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    save_unique_records_seq(
        log_anion_pi_res_diag,
        log_anion_pi_res_diag_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    save_unique_records_seq(
        log_anion_pi_res_bullshit,
        log_anion_pi_res_bullshit_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    # saveUniqueRecordsSeq( logAnionPi45, logAnionPi45Unique, 'Anion chain', 'Pi acid chain', [ 'Pi acid Code', 'Piacid id', 'Anion code', 'Anion id', 'Anion group id'] )
    # saveUniqueRecordsSeq( logAnionPiRes45, logAnionPiRes45Unique, 'Anion chain', 'Pi acid chain', [ 'Pi acid Code', 'Piacid id', 'Anion code', 'Anion id', 'Anion group id'] )

    save_unique_records_seq(
        log_methyl_pi,
        log_methyl_pi_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )
    save_unique_records_seq(
        log_methyl_pi_res,
        log_methyl_pi_res_unique,
        "Anion chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Anion code", "Anion id", "Anion group id"],
    )

    save_unique_records_seq(
        log_cation_pi,
        log_cation_pi_unique,
        "Cation chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Cation code", "Cation id"],
    )
    save_unique_records_seq(
        log_cation_pi_res,
        log_cation_pi_res_unique,
        "Cation chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Cation code", "Cation id"],
    )
    save_unique_records_seq(
        log_cation_pi_res_cylinder,
        log_cation_pi_res_cylinder_unique,
        "Cation chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Cation code", "Cation id"],
    )
    save_unique_records_seq(
        log_cation_pi_res_ring_plane,
        log_cation_pi_res_ring_plane_unique,
        "Cation chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Cation code", "Cation id"],
    )
    save_unique_records_seq(
        log_cation_pi_res45,
        log_cation_pi_res45_unique,
        "Cation chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Cation code", "Cation id"],
    )

    save_unique_records_seq(
        log_pi_pi,
        log_pi_pi_unique,
        "Pi res chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Pi res code", "Pi res id"],
    )
    save_unique_records_seq(
        log_pi_pi_res,
        log_pi_pi_res_unique,
        "Pi res chain",
        "Pi acid chain",
        ["Pi acid Code", "Piacid id", "Pi res code", "Pi res id"],
    )


##################################################################################################


def anion_pi_hist_2d(
    df,
    png_name,
    png_name_norm,
    bin,
    bin_norm,
    text="",
    min_x=0,
    max_x=4.5,
    min_h=0,
    max_h=4.5,
):
    x = df["x"].tolist()
    h = df["h"].tolist()
    plt.figure()
    plt.rcParams.update({"font.size": 16})

    plt.hist2d(
        x, h, bins=bin, cmap=plt.cm.turbo, range=[[min_x, max_x], [min_h, max_h]]
    )
    plt.colorbar()
    plt.xlabel("$\\it{x}$ / $\\AA$")
    plt.ylabel("$\\it{h}$ / $\\AA$")
    if text != "":
        plt.text(
            3.5,
            4.0,
            text,
            fontsize=20,
            color="w",
            horizontalalignment="center",
            verticalalignment="center",
            weight="bold",
        )
    plt.savefig(png_name, dpi=600, transparent=True, bbox_inches="tight")
    plt.close()

    hist, xedges, yedges = np.histogram2d(
        x, h, bins=bin_norm, range=[[min_x, max_x], [min_h, max_h]]
    )

    x_no, y_no = hist.shape
    ring_h = yedges[1] - yedges[0]

    for x_ind in range(x_no):
        ring_volume = 2 * pi * ring_h * (xedges[x_ind + 1] ** 2 - xedges[x_ind] ** 2)
        hist[x_ind, :] = hist[x_ind, :] / ring_volume

    plt.figure()
    plt.rcParams.update({"font.size": 16})
    x_grid, y_grid = np.meshgrid(xedges, yedges)
    plt.pcolormesh(x_grid, y_grid, hist.transpose(), cmap=plt.cm.turbo)
    plt.xlabel("$\\it{x}$ / $\\AA$")
    plt.ylabel("$\\it{h}$ / $\\AA$")
    plt.colorbar()
    if text != "":
        plt.text(
            3.5,
            4.0,
            text,
            fontsize=20,
            color="w",
            horizontalalignment="center",
            verticalalignment="center",
            weight="bold",
        )

    plt.savefig(png_name_norm, dpi=600, transparent=True, bbox_inches="tight")
    plt.close()


if cases2run["histogram2d"]:

    def overwiev_histograms(
        log_path,
        plot_dir,
        plot_dir_norm,
        bin,
        bin_norm,
        min_x=0,
        max_x=5.0,
        min_h=0,
        max_h=5.0,
    ):
        df = pd.read_table(log_path)

        anion_pi_hist_2d(
            df,
            join(plot_dir, basename(log_path)[:-4] + ".png"),
            join(plot_dir_norm, basename(log_path)[:-4] + ".png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[df["Pi acid Code"] != "HIS"],
            join(plot_dir, basename(log_path)[:-4] + "_noHIS.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noHIS.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[df["Pi acid Code"] != "PHE"],
            join(plot_dir, basename(log_path)[:-4] + "_noPHE.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noPHE.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[df["Pi acid Code"] != "TYR"],
            join(plot_dir, basename(log_path)[:-4] + "_noTYR.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noTYR.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[df["Pi acid Code"] != "TRP"],
            join(plot_dir, basename(log_path)[:-4] + "_noTRP.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noTRP.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[~df["Pi acid Code"].isin(["HIS", "TRP", "TYR"])],
            join(plot_dir, basename(log_path)[:-4] + "_noHaa.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noHaa.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[~df["Pi acid Code"].isin(["HIS", "TRP", "TYR", "PHE"])],
            join(plot_dir, basename(log_path)[:-4] + "_noAA.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noAA.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[
                ~df["Pi acid Code"].isin(
                    [
                        "HIS",
                        "TRP",
                        "TYR",
                        "PHE",
                        "A",
                        "G",
                        "T",
                        "C",
                        "U",
                        "I",
                        "DA",
                        "DC",
                        "DG",
                        "DT",
                        "DI",
                    ]
                )
            ],
            join(plot_dir, basename(log_path)[:-4] + "_noAA_noNU.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_noAA_noNU.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[
                df["Pi acid Code"].isin(
                    ["A", "G", "T", "C", "U", "I", "DA", "DC", "DG", "DT", "DI"]
                )
            ],
            join(plot_dir, basename(log_path)[:-4] + "_onlyNU.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_onlyNU.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )
        anion_pi_hist_2d(
            df[df["Pi acid Code"].isin(["HIS", "TRP", "TYR", "PHE"])],
            join(plot_dir, basename(log_path)[:-4] + "_onlyAA.png"),
            join(plot_dir_norm, basename(log_path)[:-4] + "_onlyAA.png"),
            bin,
            bin_norm,
            "",
            min_x,
            max_x,
            min_h,
            max_h,
        )

    main_hist_dir = join(postprocessing_dir, "hist2d")
    for png_file in glob(join(main_hist_dir, "*/*png")):
        remove(png_file)

    hist_anions_dir = join(main_hist_dir, "anions")
    hist_pi_acids_dir = join(main_hist_dir, "piAcids")
    hist_pi_acid_cation_dir = join(main_hist_dir, "piAcidsCations")
    hist_cation_dir = join(main_hist_dir, "cations")
    hist_overwiev_dir = join(main_hist_dir, "overwiev")

    hist_normalized_volume_dir = join(main_hist_dir, "normalizedVolume")

    for png_file in glob(join(hist_normalized_volume_dir, "*/*png")):
        remove(png_file)

    hist_anions_dir_normalized_volume_dir = join(hist_normalized_volume_dir, "anions")
    hist_pi_acids_dir_normalized_volume_dir = join(
        hist_normalized_volume_dir, "piAcids"
    )
    hist_pi_acid_cation_dir_normalized_volume_dir = join(
        hist_normalized_volume_dir, "piAcidsCations"
    )
    hist_cation_dir_normalized_volume_dir = join(hist_normalized_volume_dir, "cations")
    hist_overwiev_dir_normalized_volume_dir = join(
        hist_normalized_volume_dir, "overwiev"
    )

    for plots_dir in [
        hist_overwiev_dir,
        hist_anions_dir,
        hist_pi_acids_dir,
        hist_pi_acid_cation_dir,
        main_hist_dir,
        hist_cation_dir,
        hist_anions_dir_normalized_volume_dir,
        hist_pi_acids_dir_normalized_volume_dir,
        hist_cation_dir_normalized_volume_dir,
        hist_pi_acid_cation_dir_normalized_volume_dir,
        hist_overwiev_dir_normalized_volume_dir,
    ]:
        if not isdir(plots_dir):
            makedirs(plots_dir)

    bin = (500, 500)
    bin_norm = (100, 100)

    overwiev_histograms(
        log_anion_pi_unique,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        log_anion_pi_res_unique,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )

    # overwievHistograms( logAnionPi45Unique,  histOverwievDir, bin, 0, 4.5, 0, 4.5  )
    # overwievHistograms( logAnionPiRes45Unique,  histOverwievDir, bin, 0, 4.5, 0, 4.5   )

    df_cat_pi_unique = pd.read_table(log_cation_pi_unique)
    df_cat_pi_unique_metals = df_cat_pi_unique[
        ~df_cat_pi_unique["Cation code"].isin(["ARG", "LYS"])
    ]
    log_cation_pi_unique_metals = join(postprocessing_dir, "cationPiUniqueMetals.log")
    df_cat_pi_unique_metals.to_csv(log_cation_pi_unique_metals, sep="\t")
    del df_cat_pi_unique_metals

    df_cat_pi_unique_arg_lys = df_cat_pi_unique[
        df_cat_pi_unique["Cation code"].isin(["ARG", "LYS"])
    ]
    log_cat_pi_unique_arg_lys = join(postprocessing_dir, "cationPiUniqueArgLys.log")
    df_cat_pi_unique_arg_lys.to_csv(log_cat_pi_unique_arg_lys, sep="\t")
    del df_cat_pi_unique_arg_lys

    df_cat_pi_unique_dist = df_cat_pi_unique[df_cat_pi_unique["Distance"] < 5.0]
    logdf_cat_pi_unique_dist = join(postprocessing_dir, "cationPiUniqueDist.log")
    df_cat_pi_unique_dist.to_csv(logdf_cat_pi_unique_dist, sep="\t")
    del df_cat_pi_unique_dist

    overwiev_histograms(
        log_cation_pi_unique_metals,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        log_cat_pi_unique_arg_lys,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        logdf_cat_pi_unique_dist,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )

    df_cat_pi_unique = pd.read_table(log_cation_pi_res_unique)
    df_cat_pi_unique_metals = df_cat_pi_unique[
        ~df_cat_pi_unique["Cation code"].isin(["ARG", "LYS"])
    ]
    log_cation_pi_unique_metals = join(
        postprocessing_dir, "cationPiResUniqueMetals.log"
    )
    log_cation_pi_unique_metals_dist = join(
        postprocessing_dir, "cationPiResUniqueMetalsDist.log"
    )
    df_cat_pi_unique_metals.to_csv(log_cation_pi_unique_metals, sep="\t")
    df_cat_pi_unique_metals = df_cat_pi_unique_metals[
        df_cat_pi_unique_metals["Distance"] < 5.0
    ]
    df_cat_pi_unique_metals.to_csv(log_cation_pi_unique_metals_dist, sep="\t")
    del df_cat_pi_unique_metals

    df_cat_pi_unique_arg_lys = df_cat_pi_unique[
        df_cat_pi_unique["Cation code"].isin(["ARG", "LYS"])
    ]
    log_cat_pi_unique_arg_lys = join(postprocessing_dir, "cationPiResUniqueArgLys.log")
    df_cat_pi_unique_arg_lys.to_csv(log_cat_pi_unique_arg_lys, sep="\t")
    del df_cat_pi_unique_arg_lys

    df_cat_pi_unique_dist = df_cat_pi_unique[df_cat_pi_unique["Distance"] < 5.0]
    logdf_cat_pi_unique_dist = join(postprocessing_dir, "cationPiResUniqueDist.log")
    df_cat_pi_unique_dist.to_csv(logdf_cat_pi_unique_dist, sep="\t")

    cation_freq = df_cat_pi_unique_dist.groupby("Cation code").size().to_dict()
    pi_acid_cation_freq = df_cat_pi_unique_dist.groupby("Pi acid Code").size().to_dict()

    for cat in cation_freq:
        if cation_freq[cat] > 100:
            anion_pi_hist_2d(
                df_cat_pi_unique_dist[df_cat_pi_unique_dist["Cation code"] == cat],
                join(hist_cation_dir, cat + ".png"),
                join(hist_cation_dir_normalized_volume_dir, cat + ".png"),
                (100, 100),
                (20, 20),
                cat,
                0.0,
                5.0,
                0.0,
                5.0,
            )

    for pa in pi_acid_cation_freq:
        if pi_acid_cation_freq[pa] > 100:
            anion_pi_hist_2d(
                df_cat_pi_unique_dist[df_cat_pi_unique_dist["Pi acid Code"] == pa],
                join(hist_pi_acid_cation_dir, pa + ".png"),
                join(hist_pi_acid_cation_dir_normalized_volume_dir, pa + ".png"),
                (100, 100),
                (20, 20),
                pa,
                0.0,
                5.0,
                0.0,
                5.0,
            )

    overwiev_histograms(
        log_cation_pi_unique_metals,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        log_cation_pi_unique_metals_dist,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        log_cat_pi_unique_arg_lys,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        logdf_cat_pi_unique_dist,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )

    overwiev_histograms(
        log_pi_pi_unique,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        log_pi_pi_res_unique,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )

    overwiev_histograms(
        log_methyl_pi_unique,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )
    overwiev_histograms(
        log_methyl_pi_res_unique,
        hist_overwiev_dir,
        hist_overwiev_dir_normalized_volume_dir,
        bin,
        bin_norm,
    )

    # df = pd.read_table(logAnionPiRes45Unique)
    df = pd.read_table(log_anion_pi_res_unique)
    df_cylinder = pd.read_table(log_anion_pi_res_cylinder_unique)

    anion_freq = df_cylinder.groupby("Anion code").size()
    all_anions = anion_freq.to_dict()

    pi_acid_freq = df_cylinder.groupby("Pi acid Code").size()
    all_pi_acids = pi_acid_freq.to_dict()

    for anion in all_anions:
        if all_anions[anion] > 100:
            anion_pi_hist_2d(
                df[df["Anion code"] == anion],
                join(hist_anions_dir, anion + ".png"),
                join(hist_anions_dir_normalized_volume_dir, anion + ".png"),
                (100, 100),
                (20, 20),
                anion,
                0.0,
                5.0,
                0.0,
                5.0,
            )

    for pi_acid in all_pi_acids:
        if all_pi_acids[pi_acid] > 100:
            anion_pi_hist_2d(
                df[df["Pi acid Code"] == pi_acid],
                join(hist_pi_acids_dir, pi_acid + ".png"),
                join(hist_pi_acids_dir_normalized_volume_dir, pi_acid + ".png"),
                (100, 100),
                (20, 20),
                pi_acid,
                0.0,
                5.0,
                0.0,
                5.0,
            )

##################################################################################################
if cases2run["hydrogenBondAnalysis"]:
    df_anion_pi = pd.read_table(log_anion_pi_res_unique)
    df_hydrogen_bonds = pd.read_csv(log_dir + "hBonds.log", sep="\t").fillna("NA")
    h_bonds_temp = df_hydrogen_bonds[
        ~df_hydrogen_bonds["Anion code"]
        .astype(str)
        .isin(["FES", "F3S", "S3F", "9S8", "ER2", "FS4", "MSK", "SF4", "1CL", "CLF"])
    ]

    h_bonds_temp = h_bonds_temp[h_bonds_temp["Angle"] > 130.0]
    h_bonds_temp = h_bonds_temp[h_bonds_temp["Angle"] < 180.0]
    h_bonds_temp = h_bonds_temp[h_bonds_temp["Distance Don Acc"] < 3.2]
    h_bonds_temp = h_bonds_temp[h_bonds_temp["Distance H Acc"] < 2.2]

    h_bonds_temp = h_bonds_temp.rename(
        columns={
            "Donor code": "Pi acid Code",
            "Donor chain": "Pi acid chain",
            "Donor id": "Piacid id",
        }
    )

    merging_headers = [
        "PDB Code",
        "Model No",
        "Anion code",
        "Anion chain",
        "Anion id",
        "Anion group id",
        "Pi acid Code",
        "Pi acid chain",
        "Piacid id",
    ]

    auto_h_bonds = pd.merge(
        df_anion_pi[merging_headers],
        h_bonds_temp[merging_headers],
        on=merging_headers,
        how="inner",
    )

    no_auto_h_bonds = pd.merge(
        df_anion_pi, auto_h_bonds, on=merging_headers, how="left", indicator=True
    )
    no_auto_h_bonds = no_auto_h_bonds[no_auto_h_bonds["_merge"] == "left_only"]

    h_bond_anal_dir = join(postprocessing_dir, "AutoHBondsAnalysis")

    if not isdir(h_bond_anal_dir):
        makedirs(h_bond_anal_dir)

    anion_pi_hist_2d(
        no_auto_h_bonds,
        join(h_bond_anal_dir, "noAutoHBonds.png"),
        join(h_bond_anal_dir, "noAutoHBondsNorm.png"),
        (500, 500),
        (100, 100),
        "",
        0.0,
        5.0,
        0.0,
        5.0,
    )

##################################################################################################
if cases2run["ligandsAnalysis"]:
    df_anion_pi = pd.read_table(log_anion_pi_res_unique)

    anion_freq = df_anion_pi.groupby("Anion code").size().to_dict()
    pi_acid_freq = df_anion_pi.groupby("Pi acid Code").size().to_dict()

    occurences_threshold = 100
    anion_ligands = []
    pi_acid_ligands = []

    for anion in anion_freq:
        if anion_freq[anion] < occurences_threshold:
            anion_ligands.append(anion)

    for pi_acid in pi_acid_freq:
        if pi_acid_freq[pi_acid] < occurences_threshold:
            pi_acid_ligands.append(pi_acid)

    ligands_anal_dir = join(postprocessing_dir, "ligandsAnalysis")

    if not isdir(ligands_anal_dir):
        makedirs(ligands_anal_dir)

    anion_pi_hist_2d(
        df_anion_pi[df_anion_pi["Anion code"].astype(str).isin(anion_ligands)],
        join(ligands_anal_dir, "ligandsAsAnions.png"),
        join(ligands_anal_dir, "ligandsAsAnionsNorm.png"),
        (500, 500),
        (100, 100),
        "",
        0.0,
        5.0,
        0.0,
        5.0,
    )
    anion_pi_hist_2d(
        df_anion_pi[df_anion_pi["Pi acid Code"].astype(str).isin(pi_acid_ligands)],
        join(ligands_anal_dir, "ligandsAsPiAcids.png"),
        join(ligands_anal_dir, "ligandsAsPiAcidsNorm.png"),
        (500, 500),
        (100, 100),
        "",
        0.0,
        5.0,
        0.0,
        5.0,
    )


##################################################################################################
if cases2run["histogram2d-planar"]:

    def anion_pi_planar_hist_2d(
        df, png_name, bin, text="", min_x=0, max_x=90, min_y=0, max_y=180
    ):
        x = df["PlanarAngle"].tolist()
        plt.figure()
        plt.rcParams.update({"font.size": 16})
        # plt.hist2d(x, h, bins = bin, cmap=plt.cm.turbo, range= [[minX, maxX], [minY, maxY]])
        n, bins, patches = plt.hist(
            x,
            bin,
            density=False,
            range=(0, 90),
            facecolor="moccasin",
            edgecolor="orange",
        )
        # plt.colorbar()
        plt.xlabel("$\\it{\\alpha}$ / $^{\\circ}$ ")
        plt.xlim([0, 90])
        plt.ylabel("Number of occurences")
        if text != "":
            plt.text(
                70,
                0.7 * max(n),
                text,
                fontsize=20,
                color="k",
                horizontalalignment="center",
                verticalalignment="center",
                weight="bold",
            )
        plt.savefig(png_name, dpi=600, transparent=True, bbox_inches="tight")
        plt.close()

    main_planar_hist_dir = join(postprocessing_dir, "hist2d_planarAnions")
    for png_file in glob(join(main_planar_hist_dir, "*png")):
        remove(png_file)

    for plots_dir in [main_planar_hist_dir]:
        if not isdir(plots_dir):
            makedirs(plots_dir)

    anion_cation2exclude = pd.read_csv(log_anion_cation, sep="\t").fillna("NA")
    anion_cation2exclude = anion_cation2exclude[anion_cation2exclude["Distance"] < 3.0]

    df_planar_anion_pi = (
        pd.read_csv(log_planar_anion_pi, sep="\t")
        .fillna("NA")
        .rename(columns={"Angle": "PlanarAngle"})
        .drop(["Centroid x coord", "Centroid y coord", "Centroid z coord"], axis=1)
    )

    merging_headers = [
        "PDB Code",
        "Model No",
        "Anion code",
        "Anion chain",
        "Anion id",
        "Anion group id",
    ]

    sub_merged = pd.merge(
        df_planar_anion_pi,
        anion_cation2exclude[merging_headers],
        on=merging_headers,
        how="left",
        indicator=True,
    )
    df = sub_merged[sub_merged["_merge"] == "left_only"]
    df_planar_anion_pi = df.drop(["_merge"], axis=1)

    for log_ap, png_basename in zip(
        [
            log_anion_pi_res_cylinder_unique,
            log_anion_pi_res_diag_unique,
            log_anion_pi_res_ring_plane_unique,
            log_anion_pi_res_bullshit_unique,
        ],
        ["_cylinder", "_norCylinderNorPlane", "_ringPlane", "_bullshit"],
    ):
        df2merge = pd.read_table(log_ap)

        headers = [
            "PDB Code",
            "Pi acid Code",
            "Pi acid chain",
            "Piacid id",
            "CentroidId",
            "Anion code",
            "Anion chain",
            "Anion id",
            "Anion group id",
            "Model No",
        ]

        df_merged = pd.merge(df_planar_anion_pi, df2merge, on=headers)
        df_merged.to_csv(
            join(
                main_planar_hist_dir,
                "planarAnionPi" + png_basename + "_ResUniqueSeq.csv",
            ),
            sep="\t",
        )

        anion_freq = df_merged.groupby("Anion code").size()
        all_anions = anion_freq.to_dict()

        for anion in all_anions:
            if all_anions[anion] > 40:
                anion_pi_planar_hist_2d(
                    df_merged[df_merged["Anion code"] == anion],
                    join(main_planar_hist_dir, anion + png_basename + ".png"),
                    9,
                    anion,
                )


if cases2run["histograms-linear"]:

    def anion_pi_linear_hist_2d(
        df, png_name, bin, text="", min_x=0, max_x=90, min_y=0, max_y=180
    ):
        x_orig = df["LinearAngle"].tolist()
        x = []
        for x_val in x_orig:
            x.append(abs(x_val - 90))
            # if xVal > 90:
            # 	x.append(180-xVal)
            # else:
            # 	x.append(xVal)

        # h = df["DirectionalAngle"].tolist()
        plt.figure()
        plt.rcParams.update({"font.size": 16})
        # plt.hist2d(x, h, bins = bin, cmap=plt.cm.turbo, range= [[minX, maxX], [minY, maxY]])
        n, bins, patches = plt.hist(
            x,
            bin,
            density=False,
            range=(0, 90),
            facecolor="moccasin",
            edgecolor="orange",
        )
        # plt.colorbar()
        plt.xlabel("$\\it{\\alpha}$ / $^{\\circ}$ ")
        plt.xlim([0, 90])
        plt.ylabel("Number of occurences")
        if text != "":
            plt.text(
                70,
                0.7 * max(n),
                text,
                fontsize=20,
                color="k",
                horizontalalignment="center",
                verticalalignment="center",
                weight="bold",
            )
        plt.savefig(png_name, dpi=600, transparent=True, bbox_inches="tight")
        plt.close()

    main_linear_hist_dir = join(postprocessing_dir, "hist_linearAnions")
    for png_file in glob(join(main_linear_hist_dir, "*png")):
        remove(png_file)

    for plots_dir in [main_linear_hist_dir]:
        if not isdir(plots_dir):
            makedirs(plots_dir)

    anion_cation2exclude = pd.read_csv(log_anion_cation, sep="\t").fillna("NA")
    anion_cation2exclude = anion_cation2exclude[anion_cation2exclude["Distance"] < 3.0]

    df_linear_anion_pi = (
        pd.read_csv(log_linear_anion_pi, sep="\t")
        .fillna("NA")
        .rename(columns={"Angle": "LinearAngle"})
        .drop(["Centroid x coord", "Centroid y coord", "Centroid z coord"], axis=1)
    )

    merging_headers = [
        "PDB Code",
        "Model No",
        "Anion code",
        "Anion chain",
        "Anion id",
        "Anion group id",
    ]

    sub_merged = pd.merge(
        df_linear_anion_pi,
        anion_cation2exclude[merging_headers],
        on=merging_headers,
        how="left",
        indicator=True,
    )
    df = sub_merged[sub_merged["_merge"] == "left_only"]
    df_linear_anion_pi = df.drop(["_merge"], axis=1)

    for log_ap, png_basename in zip(
        [
            log_anion_pi_res_cylinder_unique,
            log_anion_pi_res_diag_unique,
            log_anion_pi_res_ring_plane_unique,
        ],
        ["_cylinder", "_norCylinderNorPlane", "_ringPlane"],
    ):
        df2merge = pd.read_table(log_ap)

        headers = [
            "PDB Code",
            "Pi acid Code",
            "Pi acid chain",
            "Piacid id",
            "CentroidId",
            "Anion code",
            "Anion chain",
            "Anion id",
            "Anion group id",
            "Model No",
        ]

        df_merged = pd.merge(df_linear_anion_pi, df2merge, on=headers)
        df_merged.to_csv(
            join(
                main_linear_hist_dir,
                "linearAnionPi" + png_basename + "_ResUniqueSeq.csv",
            ),
            sep="\t",
        )

        anion_freq = df_merged.groupby("Anion code").size()
        all_anions = anion_freq.to_dict()

        for anion in all_anions:
            if all_anions[anion] > 40:
                anion_pi_linear_hist_2d(
                    df_merged[df_merged["Anion code"] == anion],
                    join(main_linear_hist_dir, anion + png_basename + ".png"),
                    9,
                    anion,
                )

##################################################################################################

if cases2run["barplots"]:

    def anion_pi_plot_bar(data, png_name):
        plt.figure()
        plt.bar(list(data.keys()), list(data.values()), color="gold")
        plt.savefig(png_name, dpi=600, format="png", transparent=True)
        plt.close()

    logs = [
        log_anion_pi_res_cylinder_unique,
        log_anion_pi_res_ring_plane_unique,
        log_anion_pi_res_diag_unique,
        log_cation_pi_res_cylinder_unique,
        log_cation_pi_res_ring_plane_unique,
    ]
    plotbar_dir = join(postprocessing_dir, "barplots")
    if not isdir(plotbar_dir):
        makedirs(plotbar_dir)

    plotbar_dir_cation_pi = join(plotbar_dir, "cationPi")
    if not isdir(plotbar_dir_cation_pi):
        makedirs(plotbar_dir_cation_pi)

    acidicaa = ["ASP", "GLU"]
    aa = [
        "ALA",
        "CYS",
        "PHE",
        "GLY",
        "HIS",
        "ILE",
        "LYS",
        "LEU",
        "MET",
        "ASN",
        "PRO",
        "GLN",
        "ARG",
        "SER",
        "THR",
        "VAL",
        "TRP",
        "TYR",
    ]
    nu = ["A", "G", "T", "C", "U", "I", "DA", "DC", "DG", "DT", "DI"]

    a_codes = acidicaa + aa + nu
    pi_acids = ["PHE", "TYR", "HIS", "TRP"] + nu

    nbar = 10

    for log, png_basename, directory, ion_header in zip(
        logs,
        ["cylinder", "ringPlane", "norCylinderNorPlane", "cylinder", "ringPlane"],
        [
            plotbar_dir,
            plotbar_dir,
            plotbar_dir,
            plotbar_dir_cation_pi,
            plotbar_dir_cation_pi,
        ],
        ["Anion code", "Anion code", "Anion code", "Cation code", "Cation code"],
    ):
        df = pd.read_table(log)
        df2 = df.drop_duplicates(subset=["PDB Code"])

        anion_freq = df.groupby(ion_header).size().sort_values(ascending=False)
        pi_acid_freq = df.groupby("Pi acid Code").size().sort_values(ascending=False)

        if ion_header == "Anion code":
            type_freq = (
                df2.groupby("Structure type").size().sort_values(ascending=False)
            )
            type_freq_inter = (
                df.groupby("Structure type").size().sort_values(ascending=False)
            )

        anion_dict = anion_freq.head(nbar).to_dict()
        pi_acid_freq_dict = pi_acid_freq.head(nbar).to_dict()
        types_dict = type_freq.head(nbar).to_dict()

        anion_pi_plot_bar(anion_dict, join(directory, png_basename + "_topIons.png"))
        anion_pi_plot_bar(
            pi_acid_freq_dict, join(directory, png_basename + "_topPiAcids.png")
        )
        print(log)

        anion_dict = anion_freq.to_dict()
        pi_acid_freq_dict = pi_acid_freq.to_dict()

        if ion_header == "Anion code":
            types_dict = type_freq.to_dict()
            types_inter_dict = type_freq_inter.to_dict()

        for key in a_codes:
            if key in anion_dict:
                del anion_dict[key]

        for key in pi_acids:
            if key in pi_acid_freq_dict:
                del pi_acid_freq_dict[key]

        anion_dict = {
            k: v
            for k, v in sorted(
                anion_dict.items(), key=lambda item: item[1], reverse=True
            )[:nbar]
        }
        pi_acid_freq_dict = {
            k: v
            for k, v in sorted(
                pi_acid_freq_dict.items(), key=lambda item: item[1], reverse=True
            )[:nbar]
        }
        print("top ions")
        print(anion_dict)
        print("top pi acids")
        print(pi_acid_freq_dict)
        anion_pi_plot_bar(
            anion_dict, join(directory, png_basename + "_topIons_AA_NU_excluded.png")
        )
        anion_pi_plot_bar(
            pi_acid_freq_dict,
            join(directory, png_basename + "_topPiAcids_AA_NU_excluded.png"),
        )

        df3 = df[[ion_header, "Pi acid Code"]]
        pairs = (
            df3.groupby([ion_header, "Pi acid Code"])
            .size()
            .sort_values(ascending=False)
        )
        pairs_dict = pairs.head(10).to_dict()
        print(log)
        print(pairs_dict)

        if ion_header == "Anion code":
            print("PDB counts")
            print(types_dict)
            print("interaction counts")
            print(types_inter_dict)

        labels = []
        key2convert = list(pairs_dict.keys())

        for key in key2convert:
            labels.append(str(key))

        plt.figure(figsize=(16, 8))
        plt.bar(labels, list(pairs_dict.values()), color="gold")
        plt.savefig(
            join(directory, png_basename + "_top_pairs_ion_piAcid.png"),
            dpi=600,
            transparent=True,
        )

##################################################################################################

if cases2run["resolutionplot"]:
    # AnionPi_temp = pd.read_csv( logAnionPiUnique, sep = "\t").fillna("NA")
    anion_pi_temp = pd.read_csv(log_cation_pi_unique, sep="\t").fillna("NA")

    resolution_df = pd.read_csv("resolu.idx", sep=r"\s+")
    resolution_df = resolution_df.rename(columns={"IDCODE": "PDB Code"})
    anion_pi_temp = pd.merge(anion_pi_temp, resolution_df, on=["PDB Code"])
    anion_pi_temp = anion_pi_temp[
        (anion_pi_temp["RESOLUTION"] < 5) & (anion_pi_temp["RESOLUTION"] > 0)
    ]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Method" ] == "X-RAY DIFFRACTION"]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Structure type" ] == "protein"]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Anion code" ] == "GLU" ]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Pi acid Code" ] == "PHE" ]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["x"] < 1.8]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] > 1.5]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["Cation code"] == "LYS"]
    # fullSphere = AnionPi_temp.drop_duplicates(subset = ['PDB Code', 'Pi acid Code', 'Piacid id', 'Anion code', 'Anion id', 'Anion group id'])
    full_sphere = anion_pi_temp

    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "x" ] > 0.0 ]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "x" ] < 1.8 ]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Angle" ] < 45.0 ]
    anion_pi_temp = anion_pi_temp[anion_pi_temp["h"] < 3.5]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "h" ] < 3.5 ]
    # AnionPi_temp = AnionPi_temp[ AnionPi_temp [ "Distance" ] < 4.5 ]

    # insideCone = AnionPi_temp.drop_duplicates(subset = ['PDB Code', 'Pi acid Code', 'Piacid id', 'Anion code', 'Anion id', 'Anion group id'])
    inside_cone = anion_pi_temp
    res_min = min(full_sphere["RESOLUTION"])
    res_max = max(full_sphere["RESOLUTION"])

    nbins = 30

    full_sphere_counts, full_sphere_bins = np.histogram(
        full_sphere["RESOLUTION"], bins=nbins, range=(res_min, res_max)
    )
    inside_cone_counts, inside_cone_bins = np.histogram(
        inside_cone["RESOLUTION"], bins=nbins, range=(res_min, res_max)
    )

    print(full_sphere_bins)
    print(inside_cone_bins)
    cone2full_sphere = []
    i = 0
    x = []
    full_x = []

    counts_per_pdb_sphere = []
    counts_per_pdb_cone = []
    pdb_in_cone2pdb_in_sphere = []

    for cone, sphere in zip(inside_cone_counts, full_sphere_counts):
        if sphere > 10 and cone > 10:
            cone2full_sphere.append(100 * cone / sphere)
            x.append((inside_cone_bins[i] + inside_cone_bins[i + 1]) / 2)
            pdb_in_res_range_sphere = len(
                full_sphere[
                    (full_sphere["RESOLUTION"] > inside_cone_bins[i])
                    & (full_sphere["RESOLUTION"] < inside_cone_bins[i + 1])
                ]
                .drop_duplicates(subset=["PDB Code"])
                .index
            )
            pdb_in_res_range_cone = len(
                inside_cone[
                    (inside_cone["RESOLUTION"] > inside_cone_bins[i])
                    & (inside_cone["RESOLUTION"] < inside_cone_bins[i + 1])
                ]
                .drop_duplicates(subset=["PDB Code"])
                .index
            )
            counts_per_pdb_sphere.append(sphere / pdb_in_res_range_sphere)
            counts_per_pdb_cone.append(cone / pdb_in_res_range_sphere)
            pdb_in_cone2pdb_in_sphere.append(
                pdb_in_res_range_cone / pdb_in_res_range_sphere
            )

        full_x.append((inside_cone_bins[i] + inside_cone_bins[i + 1]) / 2)
        i += 1

    plt.figure()
    plt.plot(x, cone2full_sphere)
    plt.xlabel("resolution ${\\AA}$")
    plt.savefig(join(postprocessing_dir, "resolution.png"), dpi=600, transparent=True)
    plt.show()

################################################################################

if cases2run["occurencesTable"]:

    def get_freq(df):
        dfanion = df.drop_duplicates(subset=["Sequence ID 1", "Anion code", "Anion id"])
        dfpiacid = df.drop_duplicates(
            subset=["Sequence ID 2", "Pi acid Code", "Piacid id"]
        )

        anion_freq = dfanion.groupby("Anion code").size().sort_values(ascending=False)
        pi_acid_freq = (
            dfpiacid.groupby("Pi acid Code").size().sort_values(ascending=False)
        )

        anion_dict = anion_freq.to_dict()
        pi_acid_freq_dict = pi_acid_freq.to_dict()

        return anion_dict, pi_acid_freq_dict

    def get_freq_cation(df):
        dfcation = df.drop_duplicates(
            subset=["Sequence ID 1", "Cation code", "Cation id"]
        )
        dfpiacid = df.drop_duplicates(
            subset=["Sequence ID 1", "Pi acid Code", "Piacid id"]
        )

        cation_freq = (
            dfcation.groupby("Cation code").size().sort_values(ascending=False)
        )
        pi_acid_freq = (
            dfpiacid.groupby("Pi acid Code").size().sort_values(ascending=False)
        )

        cation_dict = cation_freq.to_dict()
        pi_acid_freq_dict = pi_acid_freq.to_dict()

        return cation_dict, pi_acid_freq_dict

    df_sphere = pd.read_table(log_anion_pi_res_unique)
    anion_sphere, pi_acid_sphere = get_freq(df_sphere)

    print("Number of unique resnames anions in sphere ", len(list(anion_sphere.keys())))
    print(
        "Number of unique resnames quadrupoles in sphere ",
        len(list(pi_acid_sphere.keys())),
    )

    for ap_log in [
        log_anion_pi_res_cylinder_unique,
        log_anion_pi_res_diag_unique,
        log_anion_pi_res_ring_plane_unique,
    ]:
        operating_dir = ap_log[:-4] + "_tables"
        if not isdir(operating_dir):
            makedirs(operating_dir)

        df_cylinder = pd.read_table(ap_log)
        anion_cylinder, pi_acid_cylinder = get_freq(df_cylinder)

        selected_res_anions = list(anion_cylinder.keys())

        table = open(join(operating_dir, "anionsOccurencesFull.csv"), "w")
        table.write(
            "\t".join(["Residue", "in sphere", "in cylinder", "cylinder/sphere"]) + "\n"
        )
        for res in selected_res_anions:
            table.write(res + "\t")
            numbers = [
                anion_sphere[res],
                anion_cylinder[res],
                100 * anion_cylinder[res] / anion_sphere[res],
            ]
            table.write("\t".join([str(num) for num in numbers]))
            table.write("\n")

        table.close()

        selected_res_pi_acids = list(pi_acid_cylinder.keys())
        table = open(join(operating_dir, "piAcidOccurencesFull.csv"), "w")
        table.write(
            "\t".join(["Residue", "in sphere", "in cylinder", "cylinder/sphere"]) + "\n"
        )
        for res in selected_res_pi_acids:
            table.write(res + "\t")
            numbers = [
                pi_acid_sphere[res],
                pi_acid_cylinder[res],
                100 * pi_acid_cylinder[res] / pi_acid_sphere[res],
            ]
            table.write("\t".join([str(num) for num in numbers]))
            table.write("\n")

        table.close()

        table = open(join(operating_dir, "anionsOccurencesSmall.csv"), "w")
        table.write(
            "\t".join(["Residue", "in sphere", "in cylinder", "cylinder/sphere"]) + "\n"
        )
        for res in selected_res_anions:
            if anion_cylinder[res] >= 100:
                table.write(res + "\t")
                numbers = [
                    anion_sphere[res],
                    anion_cylinder[res],
                    100 * anion_cylinder[res] / anion_sphere[res],
                ]
                table.write("\t".join([str(num) for num in numbers]))
                table.write("\n")

        table.close()

        table = open(join(operating_dir, "piAcidOccurencesSmall.csv"), "w")
        table.write(
            "\t".join(["Residue", "in sphere", "in cylinder", "cylinder/sphere"]) + "\n"
        )
        for res in selected_res_pi_acids:
            if pi_acid_cylinder[res] >= 100:
                table.write(res + "\t")
                numbers = [
                    pi_acid_sphere[res],
                    pi_acid_cylinder[res],
                    100 * pi_acid_cylinder[res] / pi_acid_sphere[res],
                ]
                table.write("\t".join([str(num) for num in numbers]))
                table.write("\n")

        table.close()

    df_sphere = pd.read_table(log_cation_pi_res45_unique)
    df_cylinder = pd.read_table(log_cation_pi_res_cylinder_unique)

    cation_sphere, pi_acid_cation_sphere = get_freq_cation(df_sphere)
    cation_cylinder, pi_acid_cation_cylinder = get_freq_cation(df_cylinder)

    selected_res_cations = list(cation_cylinder.keys())
    table = open(join(res_unique_dir, "cationsOccurencesFull.csv"), "w")
    table.write(
        "\t".join(["Residue", "in sphere", "in cylinder", "cylinder/sphere"]) + "\n"
    )
    for res in selected_res_cations:
        table.write(res + "\t")
        numbers = [
            cation_sphere[res],
            cation_cylinder[res],
            100 * cation_cylinder[res] / cation_sphere[res],
        ]
        table.write("\t".join([str(num) for num in numbers]))
        table.write("\n")

    table.close()

    selected_res_pi_acids = list(pi_acid_cation_cylinder.keys())
    table = open(join(res_unique_dir, "piAcidCationOccurencesFull.csv"), "w")
    table.write(
        "\t".join(["Residue", "in sphere", "in cylinder", "cylinder/sphere"]) + "\n"
    )
    for res in selected_res_pi_acids:
        table.write(res + "\t")
        numbers = [
            pi_acid_cation_sphere[res],
            pi_acid_cation_cylinder[res],
            100 * pi_acid_cation_cylinder[res] / pi_acid_cation_sphere[res],
        ]
        table.write("\t".join([str(num) for num in numbers]))
        table.write("\n")

    table.close()
################################################################################
if cases2run["occurencesPairs"]:
    for log_ap in [
        log_anion_pi_res_cylinder_unique,
        log_anion_pi_res_diag_unique,
        log_anion_pi_res_ring_plane_unique,
    ]:
        df = pd.read_table(log_ap)

        df2 = df[["Anion code", "Pi acid Code"]]

        pairs = (
            df2.groupby(["Anion code", "Pi acid Code"])
            .size()
            .sort_values(ascending=False)
        )

        pairs_dict = pairs.to_dict()

        anion_code = df["Anion code"].drop_duplicates()
        all_anion_code = anion_code.tolist()

        pi_acid_code = df["Pi acid Code"].drop_duplicates()
        all_pi_acid_code = pi_acid_code.tolist()

        acidicaa = ["ASP", "GLU"]
        aa = [
            "ALA",
            "CYS",
            "PHE",
            "GLY",
            "HIS",
            "ILE",
            "LYS",
            "LEU",
            "MET",
            "ASN",
            "PRO",
            "GLN",
            "ARG",
            "SER",
            "THR",
            "VAL",
            "TRP",
            "TYR",
        ]
        nu = ["A", "G", "T", "C", "U", "I", "DA", "DC", "DG", "DT", "DI"]

        a_codes = acidicaa + aa + nu
        pi_acids = ["PHE", "TYR", "HIS", "TRP"] + nu

        tabela = open(log_ap[:-4] + "_tabela.csv", "w")
        tabela.write("piacid\t")

        for a in a_codes:
            tabela.write(a + "\t")
        tabela.write("Others\n")

        grand_total = pairs.sum()
        for piacid in pi_acids:
            tabela.write(piacid + "\t")
            total = 0
            for key in pairs_dict:
                if key[1] == piacid:
                    total += pairs_dict[key]

            for anion in a_codes:
                key = (anion, piacid)
                if key in pairs_dict:
                    anion_piacid_counts = pairs_dict[key]
                    anion_piacid_counts_str = str(anion_piacid_counts)
                    tabela.write(anion_piacid_counts_str + "\t")
                    total -= anion_piacid_counts
                    grand_total -= anion_piacid_counts
                else:
                    tabela.write("0\t")

            tabela.write(str(total) + "\n")
            grand_total -= total
        tabela.write("Others\t")

        for anion in a_codes:
            total = 0
            for key in pairs_dict:
                if key[0] == anion:
                    total += pairs_dict[key]

            for piacid in pi_acids:
                key = (anion, piacid)
                if key in pairs_dict:
                    piacid_counts = pairs_dict[key]
                    total -= piacid_counts

            tabela.write(str(total) + "\t")
            grand_total -= total

        tabela.write(str(grand_total) + "\n")
        tabela.close()
################################################################################
if cases2run["chainNeoghbors"]:
    cnbar_dir = join(postprocessing_dir, "chainNeighbors")
    if not isdir(cnbar_dir):
        makedirs(cnbar_dir)

    for png_file in glob(join(cnbar_dir, "*png")):
        remove(png_file)

    def get_residue_id_diff_data_frame(log_name):
        anion_pi_temp = pd.read_table(log_name)
        anion_pi_temp = anion_pi_temp[
            anion_pi_temp["Pi acid Code"]
            .astype(str)
            .isin(
                [
                    "PHE",
                    "HIS",
                    "TRP",
                    "TYR",
                    "A",
                    "G",
                    "T",
                    "C",
                    "U",
                    "I",
                    "DA",
                    "DC",
                    "DG",
                    "DT",
                    "DI",
                ]
            )
        ]
        anion_pi_temp = anion_pi_temp[
            anion_pi_temp["Anion code"]
            .astype(str)
            .isin(
                [
                    "ASP",
                    "GLU",
                    "A",
                    "G",
                    "T",
                    "C",
                    "U",
                    "I",
                    "DA",
                    "DC",
                    "DG",
                    "DT",
                    "DI",
                ]
            )
        ]
        anion_pi_temp = anion_pi_temp[
            anion_pi_temp["Pi acid chain"] == anion_pi_temp["Anion chain"]
        ]

        anion_pi_temp["chainDist"] = (
            anion_pi_temp["Piacid id"] - anion_pi_temp["Anion id"]
        )
        # AnionPi_temp["chainDist"] = AnionPi_temp["chainDist"].abs()

        anion_pi_temp = anion_pi_temp[
            (anion_pi_temp["chainDist"] < 100) & (anion_pi_temp["chainDist"] > -100)
        ]
        return anion_pi_temp

    df_cylinder = get_residue_id_diff_data_frame(log_anion_pi_res_cylinder_unique)
    df_plane = get_residue_id_diff_data_frame(log_anion_pi_res_ring_plane_unique)
    df_nor = get_residue_id_diff_data_frame(log_anion_pi_res_diag_unique)
    # print("Size of the zero bar")
    # print( len(AnionPi_temp[ AnionPi_temp[ "chainDist" ] == 0 ].index) )
    # AnionPi_temp[ AnionPi_temp[ "chainDist" ] == 0 ].to_csv( join(cnbarDir, "zeroDiffChain.csv"), sep = "\t")

    for df_ap, csv_basename in zip(
        [df_cylinder, df_nor, df_plane],
        ["_cylinder.csv", "_norCylinderNorPlane.csv", "_ringPlane.csv"],
    ):
        df_close_anions = df_ap[
            df_ap["Pi acid Code"].astype(str).isin(["PHE", "HIS", "TRP", "TYR"])
        ]
        df_close_anions = df_close_anions[
            df_close_anions["Anion code"].astype(str).isin(["ASP", "GLU"])
        ]
        df_close_anions = df_close_anions[
            (df_close_anions["chainDist"] < 6)
            & (df_close_anions["chainDist"] > -6)
            & (df_close_anions["chainDist"] != 0)
        ]

        df_close_anions.to_csv(join(cnbar_dir, "closeAnions" + csv_basename), sep="\t")

        df_close_nu = df_ap[
            df_ap["Pi acid Code"]
            .astype(str)
            .isin(["A", "G", "T", "C", "U", "I", "DA", "DC", "DG", "DT", "DI"])
        ]
        df_close_nu = df_close_nu[
            df_close_nu["Anion code"]
            .astype(str)
            .isin(["A", "G", "T", "C", "U", "I", "DA", "DC", "DG", "DT", "DI"])
        ]
        df_close_nu = df_close_nu[
            (df_close_nu["chainDist"] < 6)
            & (df_close_nu["chainDist"] > -6)
            & (df_close_nu["chainDist"] != 0)
        ]

        df_close_nu.to_csv(join(cnbar_dir, "closeNUs" + csv_basename), sep="\t")

    for anion in ["ASP", "GLU"]:
        for pi_acid in ["PHE", "HIS", "TRP", "TYR"]:
            for temp_ap, png_banename in zip(
                [df_cylinder, df_nor, df_plane],
                ["_cylinder.png", "_norCylinderNorPlane.png", "_ringPlane.png"],
            ):
                temp = temp_ap[
                    (temp_ap["Anion code"] == anion)
                    & (temp_ap["Pi acid Code"] == pi_acid)
                ]

                freq = temp.groupby("chainDist").size().sort_values(ascending=False)
                data = freq.to_dict()

                plt.figure()
                plt.bar(list(data.keys()), list(data.values()), color="gold")
                plt.xlabel("$ \\Delta_{rID - aID}$")
                plt.ylabel("Pairs")
                plt.text(
                    70,
                    0.7 * max(data.values()),
                    anion + "-" + pi_acid,
                    fontsize=16,
                    color="k",
                    horizontalalignment="center",
                    verticalalignment="center",
                    weight="bold",
                )
                plt.text(
                    -70,
                    0.7 * max(data.values()),
                    pi_acid + "-" + anion,
                    fontsize=16,
                    color="k",
                    horizontalalignment="center",
                    verticalalignment="center",
                    weight="bold",
                )
                plt.savefig(
                    join(cnbar_dir, anion + "_" + pi_acid + png_banename),
                    dpi=600,
                    format="png",
                    transparent=True,
                    bbox_inches="tight",
                )
                plt.close()

    all_nu = ["A", "G", "T", "C", "U", "I", "DA", "DC", "DG", "DT", "DI"]
    all_nu_dna = ["DA", "DC", "DG", "DT", "DI"]
    all_nu_rna = ["A", "G", "T", "C", "U", "I"]

    for temp_ap, png_banename in zip(
        [df_cylinder, df_nor, df_plane],
        ["_cylinder.png", "_norCylinderNorPlane.png", "_ringPlane.png"],
    ):
        temp = temp_ap[
            (temp_ap["Anion code"].astype(str).isin(all_nu))
            & (temp_ap["Pi acid Code"].astype(str).isin(all_nu))
            & (temp_ap["chainDist"] > -25)
            & (temp_ap["chainDist"] < 25)
        ]

        freq = temp.groupby("chainDist").size().sort_values(ascending=False)
        data = freq.to_dict()

        plt.figure()
        plt.bar(list(data.keys()), list(data.values()), color="gold")
        plt.xlabel("$ \\Delta_{rID - aID}$")
        plt.ylabel("Pairs")
        # plt.text(70, 0.7*max(data.values()), anion + "-"+ piAcid, fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        # plt.text(-70, 0.7*max(data.values()), piAcid + "-"+ anion , fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        plt.savefig(
            join(cnbar_dir, "onlyNU" + png_banename),
            dpi=600,
            format="png",
            transparent=True,
            bbox_inches="tight",
        )
        plt.close()

    for temp_ap, png_banename in zip(
        [df_cylinder, df_nor, df_plane],
        ["_cylinder.png", "_norCylinderNorPlane.png", "_ringPlane.png"],
    ):
        temp = temp_ap[
            (temp_ap["Anion code"].astype(str).isin(all_nu_dna))
            & (temp_ap["Pi acid Code"].astype(str).isin(all_nu_dna))
            & (temp_ap["chainDist"] > -25)
            & (temp_ap["chainDist"] < 25)
        ]

        freq = temp.groupby("chainDist").size().sort_values(ascending=False)
        data = freq.to_dict()

        plt.figure()
        plt.bar(list(data.keys()), list(data.values()), color="gold")
        plt.xlim([-25, 25])
        plt.xlabel("$ \\Delta_{rID - aID}$")
        plt.ylabel("Pairs")
        # plt.text(70, 0.7*max(data.values()), anion + "-"+ piAcid, fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        # plt.text(-70, 0.7*max(data.values()), piAcid + "-"+ anion , fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        plt.savefig(
            join(cnbar_dir, "onlyDNA" + png_banename),
            dpi=600,
            format="png",
            transparent=True,
            bbox_inches="tight",
        )
        plt.close()

    for temp_ap, png_banename in zip(
        [df_cylinder, df_nor, df_plane],
        ["_cylinder.png", "_norCylinderNorPlane.png", "_ringPlane.png"],
    ):
        temp = temp_ap[
            (temp_ap["Anion code"].astype(str).isin(all_nu_rna))
            & (temp_ap["Pi acid Code"].astype(str).isin(all_nu_rna))
            & (temp_ap["chainDist"] > -25)
            & (temp_ap["chainDist"] < 25)
        ]

        freq = temp.groupby("chainDist").size().sort_values(ascending=False)
        data = freq.to_dict()

        plt.figure()
        plt.bar(list(data.keys()), list(data.values()), color="gold")
        plt.xlim([-25, 25])
        plt.xlabel("$ \\Delta_{rID - aID}$")
        plt.ylabel("Pairs")
        # plt.text(70, 0.7*max(data.values()), anion + "-"+ piAcid, fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        # plt.text(-70, 0.7*max(data.values()), piAcid + "-"+ anion , fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        plt.savefig(
            join(cnbar_dir, "onlyRNA" + png_banename),
            dpi=600,
            format="png",
            transparent=True,
            bbox_inches="tight",
        )
        plt.close()

    for temp_ap, png_banename in zip(
        [df_cylinder, df_nor, df_plane],
        ["_cylinder.png", "_norCylinderNorPlane.png", "_ringPlane.png"],
    ):
        temp = temp_ap[
            (temp_ap["Anion code"].astype(str).isin(["ASP", "GLU"]))
            & (temp_ap["Pi acid Code"].astype(str).isin(["PHE", "HIS", "TRP", "TYR"]))
            & (temp_ap["chainDist"] > -25)
            & (temp_ap["chainDist"] < 25)
        ]

        freq = temp.groupby("chainDist").size().sort_values(ascending=False)
        data = freq.to_dict()

        plt.figure()
        plt.bar(list(data.keys()), list(data.values()), color="gold")
        plt.xlabel("$ \\Delta_{rID - aID}$")
        plt.ylabel("Pairs")
        # plt.text(70, 0.7*max(data.values()), anion + "-"+ piAcid, fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        # plt.text(-70, 0.7*max(data.values()), piAcid + "-"+ anion , fontsize = 16, color='k',horizontalalignment='center', verticalalignment='center', weight='bold')
        plt.savefig(
            join(cnbar_dir, "onlyAA" + png_banename),
            dpi=600,
            format="png",
            transparent=True,
            bbox_inches="tight",
        )
        plt.close()
