"""Backward-compatible names for scripts recorded before the PEP 8 rename.

Scripts generated by the plugin used to start with
``from simpleFilters import *`` and call the camelCase functions below. New
scripts import from ``simple_filters`` instead.
"""

from simple_filters import *  # noqa: F403
from simple_filters import (
    no_aa_in_anions,
    no_aa_in_cations,
    no_aa_in_h_acceptors,
    no_aa_in_h_donors,
    no_aa_in_pi_acids,
    no_aa_in_pi_res,
    no_nu_in_anions,
    no_nu_in_h_acceptors,
    no_nu_in_h_donors,
    no_nu_in_pi_acids,
    no_nu_in_pi_res,
    only_anions,
    only_complexes,
    simple_merge,
)

noAAinPiAcids = no_aa_in_pi_acids
noAAinPiRes = no_aa_in_pi_res
noAAinAnions = no_aa_in_anions
noNUinAnions = no_nu_in_anions
noNUinPiAcids = no_nu_in_pi_acids
noNUinPiRes = no_nu_in_pi_res
noAAinHAcceptors = no_aa_in_h_acceptors
noNUinHAcceptors = no_nu_in_h_acceptors
noAAinHDonors = no_aa_in_h_donors
noNUinHDonors = no_nu_in_h_donors
noAAinCations = no_aa_in_cations
onlyAnions = only_anions
onlyComplexes = only_complexes
simpleMerge = simple_merge
